AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Metrics/LineLength:
  Max: 130
Style/Documentation:
  Enabled: false
