AllCops:
  Exclude:
    - Rakefile
    - bin/**/*
    - db/**/*
    - config/**/*
    - spec/**/*
    - tmp/**/*
    - app/controllers/users/**
    - app/helpers/devise_helper.rb
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Metrics/LineLength:
  Max: 130
Style/Documentation:
  Enabled: false
Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
